ALTER TABLE c_job
  ADD COLUMN province  VARCHAR(50)  DEFAULT NULL COMMENT '省',
  ADD COLUMN city      VARCHAR(50)  DEFAULT NULL COMMENT '市',
  ADD COLUMN district  VARCHAR(50)  DEFAULT NULL COMMENT '区',
  ADD COLUMN address   VARCHAR(200) DEFAULT NULL COMMENT '详细地址',
  ADD COLUMN latitude  DECIMAL(10,7) DEFAULT NULL COMMENT '纬度',
  ADD COLUMN longitude DECIMAL(10,7) DEFAULT NULL COMMENT '经度';
