ALTER TABLE c_job
  ADD COLUMN schedule_info TEXT DEFAULT NULL COMMENT '排班JSON';

ALTER TABLE c_job
  ADD COLUMN headcount INT DEFAULT NULL COMMENT '招聘人数',
  ADD COLUMN deadline DATETIME DEFAULT NULL COMMENT '报名截止时间';
