ALTER TABLE jobs
  ADD COLUMN province  VARCHAR(50)  DEFAULT NULL COMMENT '省' AFTER location,
  ADD COLUMN city      VARCHAR(50)  DEFAULT NULL COMMENT '市' AFTER province,
  ADD COLUMN district  VARCHAR(50)  DEFAULT NULL COMMENT '区' AFTER city,
  ADD COLUMN address   VARCHAR(200) DEFAULT NULL COMMENT '详细地址（街道门牌号）' AFTER district,
  ADD COLUMN latitude  DECIMAL(10,7) DEFAULT NULL COMMENT '纬度' AFTER address,
  ADD COLUMN longitude DECIMAL(10,7) DEFAULT NULL COMMENT '经度' AFTER address;
