server:
  port: 8081

spring:
  application:
    name: enterprise-service

  datasource:
    url: jdbc:mysql://localhost:3306/parttime_enterprise?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.parttime.enterprise.infrastructure.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
