CREATE TABLE settlement_bills (
    id                  BIGINT AUTO_INCREMENT PRIMARY KEY,
    company_id          BIGINT NOT NULL,
    job_id              BIGINT NOT NULL,
    shift_id            BIGINT NOT NULL,
    worker_id           BIGINT NOT NULL,
    worker_name         VARCHAR(100) DEFAULT NULL,
    shift_date          DATE NOT NULL,
    start_time          TIME NOT NULL,
    end_time            TIME NOT NULL,
    total_hours         DECIMAL(10,2) DEFAULT NULL,
    rate_type           VARCHAR(20) DEFAULT NULL,
    rate_amount         DECIMAL(10,2) DEFAULT NULL,
    scheduled_pay       DECIMAL(10,2) DEFAULT NULL,
    actual_pay          DECIMAL(10,2) NOT NULL,
    serial_number       VARCHAR(64) NOT NULL COMMENT '系统流水号',
    third_party_serial_no VARCHAR(128) DEFAULT NULL COMMENT '第三方流水号',
    third_party_platform  VARCHAR(50) DEFAULT NULL COMMENT '第三方支付平台',
    status              VARCHAR(20) NOT NULL DEFAULT 'PAYING' COMMENT 'PAYING/PAID/FAILED',
    paid_at             DATETIME DEFAULT NULL,
    created_at          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_company_id (company_id),
    INDEX idx_job_id (job_id),
    INDEX idx_shift_id (shift_id),
    INDEX idx_worker_id (worker_id),
    INDEX idx_serial_number (serial_number),
    INDEX idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
