CREATE TABLE IF NOT EXISTS worker_balances (
    worker_id BIGINT PRIMARY KEY,
    balance DECIMAL(12,2) NOT NULL DEFAULT 0.00 COMMENT '可用余额',
    total_earned DECIMAL(12,2) NOT NULL DEFAULT 0.00 COMMENT '累计收入',
    total_withdrawn DECIMAL(12,2) NOT NULL DEFAULT 0.00 COMMENT '累计提现',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
